export const SITE = {
  name: "Tuning Center Örebro",
  phone: "0790790007",
  phoneDisplay: "079 079 00 07",
  email: "Tuningcenter59@gmail.com",
  instagram: "https://www.instagram.com/tuningcenterorebro",
  instagramHandle: "@tuningcenterorebro",
  facebook: "https://www.facebook.com/tuningcenterorebro",
  facebookHandle: "Tuning Center Örebro",
  address: "Ymergatan 3A",
  postalCity: "692 35 Kumla",
  mapUrl: "https://www.google.com/maps/dir/?api=1&destination=Ymergatan+3A%2C+692+35+Kumla",
  city: "Kumla",
  hours: [
    ["Måndag", "07–20"],
    ["Tisdag", "07–20"],
    ["Onsdag", "07–20"],
    ["Torsdag", "07–20"],
    ["Fredag", "07–20"],
    ["Lördag", "09–18"],
    ["Söndag", "Stängt"],
  ],
} as const;
