/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KalkylatorRouteImport } from './routes/kalkylator'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as ApiPublicKontaktRouteImport } from './routes/api/public/kontakt'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkylatorRoute = KalkylatorRouteImport.update({
  id: '/kalkylator',
  path: '/kalkylator',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKontaktRoute = ApiPublicKontaktRouteImport.update({
  id: '/api/public/kontakt',
  path: '/api/public/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kalkylator': typeof KalkylatorRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster': typeof TjansterRoute
  '/api/public/kontakt': typeof ApiPublicKontaktRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kalkylator': typeof KalkylatorRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster': typeof TjansterRoute
  '/api/public/kontakt': typeof ApiPublicKontaktRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kalkylator': typeof KalkylatorRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster': typeof TjansterRoute
  '/api/public/kontakt': typeof ApiPublicKontaktRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kalkylator'
    | '/kontakt'
    | '/om-oss'
    | '/sitemap.xml'
    | '/tjanster'
    | '/api/public/kontakt'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kalkylator'
    | '/kontakt'
    | '/om-oss'
    | '/sitemap.xml'
    | '/tjanster'
    | '/api/public/kontakt'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/kalkylator'
    | '/kontakt'
    | '/om-oss'
    | '/sitemap.xml'
    | '/tjanster'
    | '/api/public/kontakt'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KalkylatorRoute: typeof KalkylatorRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TjansterRoute: typeof TjansterRoute
  ApiPublicKontaktRoute: typeof ApiPublicKontaktRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkylator': {
      id: '/kalkylator'
      path: '/kalkylator'
      fullPath: '/kalkylator'
      preLoaderRoute: typeof KalkylatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kontakt': {
      id: '/api/public/kontakt'
      path: '/api/public/kontakt'
      fullPath: '/api/public/kontakt'
      preLoaderRoute: typeof ApiPublicKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KalkylatorRoute: KalkylatorRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TjansterRoute: TjansterRoute,
  ApiPublicKontaktRoute: ApiPublicKontaktRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
